name: Run Python Script

on:
  workflow_dispatch:  # This triggers the action manually (or via an API call)

jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Choose your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # If you have dependencies

      - name: Run the Python script
        run: |
          python script.py  # Run your Python script
